### ISSUE TITLE
SSL connection with validation of SAN-entries in the certificate in newer python versions

### ISSUE THREAD

**Issue by AugustVomFass** [exasol/pyexasol#62] opened 2020-12-17 15:25 UTC
We encounter some issues when we try to run pyExasol in combination with tls-encryption and validating SAN entries in the certificate, but only in newer python-versions... starting with python 3.7.9 the method we used to connect is not working anymore.

The issue is related to https://github.com/badoo/pyexasol/issues/61

See details below..

Running py exasol with option encrytped 
and check_hostname=True doesn't work with certificates where DNS Names are in Subject Alternative Name (SAN) .

---------------------------------------------------------------------

running with PYTHON 3.8.6 und Python 3.6.4 and Python 3.7.9 on Linux

check_hostname": True — throws error
check_hostname": False — works without validation of DNS Names (SNI entries)

import ssl
import pyexasol

c = pyexasol.connect(dsn='hostname_with_domain:8563',
                     user='USER',
                     password='PWD',
                     debug=True,
                     encryption=True,
                     websocket_sslopt={"cert_reqs": ssl.CERT_REQUIRED,
                                       "check_hostname": True,
                                       "ca_certs": "C:\\test\\cert\\cacert.pem"}
)

res = c.execute('SELECT * FROM EXA_ALL_TABLES ')
rows = res.fetchmany(10)
for row in rows:
    print(rows)

c.close(True)

-------------------------------------------------------------------------------
------------------------------------------
Running Command with Python 3.6.4

pyexasol.exceptions.ExaConnectionFailedError:
(
    message     =>  Could not connect to Exasol: hostname 'xx.xxx.xxx.xxx' doesn't match either of 'hostname1.dns.com', 'hostname2.dns.com', 'CertreqId-xxxxxxxxxx'

---------------------------------------------------

Running Command with Python 3.8.6 and 3.7.9
pyexasol.exceptions.ExaConnectionFailedError:
(
    message     =>  Could not connect to Exasol: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for 'xx.xxx.xxx.xxx'. (_ssl.c:1124)
    dsn         =>  hostname_with_domain:8563
    user        =>  USER
    schema      =>
    session_id  =>
)

-----------------------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------

Running Python 3.6.4 with option

ssl.match_hostname = lambda cert, hostname: True

works !!!

-----------------------------------------------------------------

(venv38) pip list
Package Version
---------------- ---------
certifi 2020.12.5
cffi 1.14.4
chardet 3.0.4
cryptography 3.2.1
EXASOL-DB-API 6.0.0
gevent 20.9.0
greenlet 0.4.17
idna 2.10
pip 20.3.1
pproxy 2.5
psutil 5.7.3
pyasn1 0.4.8
pycparser 2.20
pyexasol 0.15.1
pyOpenSSL 20.0.0
requests 2.25.0
rsa 4.6
setuptools 47.1.0
six 1.15.0
SQLAlchemy 1.3.6
urllib3 1.26.2
websocket 0.2.1
websocket-client 0.57.0
zope.event 4.5.0
zope.interface 5.2.0

-----------------------------------------------------------------

**Comment by wildraid** [comment] 2020-12-17 22:37
@AugustVomFass , I think the problem is related to this issue: https://bugs.python.org/issue34440

PyEXASOL resolves hostnames, extracts all IP addresses into list and shuffles it: https://github.com/badoo/pyexasol/blob/master/pyexasol/connection.py#L702

And all the connections are attempted using raw IP addresses from this point. This is necessary to support the connection redundancy properly.

It might be possible to set custom `server_hostname` parameter here: https://github.com/websocket-client/websocket-client/blob/29c15714ac9f5272e1adefc9c99b83420b409f63/websocket/_http.py#L243

But I do not see an easy way to do so in the current implementation of websocket-client. It just parses the connection URL and sends hostname obtained from it. And I do not see any updates for this library for a long time, so the chances for "Pull request" are slim.

I see the following possible solutions right now:

1) Add raw IP address entries to certificate.
2) Disable host verification.

And an ultimate solution is to setup an external secured tunnel to Exasol servers and use it instead of SSL. It is kinda awkward for connections to DBMS which is not designed to be available from public IP addresses in the internet.

**Comment by wildraid** [comment] 2020-12-30 10:54
@AugustVomFass , are any of possible solutions work for you?

If not, I'll consider switching to different websocket client implementation. Naturally, it will take a longer time to develop and test edge cases. But maybe I'll have to do it eventually anyway, since the original `websocket-client` is no longer maintained.

**Comment by tkilias** [comment] 2021-01-07 17:01
Hi @wildraid ,

I also looked a bit into this issue. I found the following entry in the [changelog](https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-0-beta-2) of Python 3.8.

> bpo-37463: ssl.match_hostname() no longer accepts IPv4 addresses with
> additional text after the address and only quad-dotted notation without
> trailing whitespaces. Some inet_aton() implementations ignore whitespace
> and all data after whitespace, e.g. ‘127.0.0.1 whatever’.

From there, I found the [bug tracker entry](https://bugs.python.org/issue37463) and the [security notification](https://python-security.readthedocs.io/vuln/ssl-match_hostname-ipv4-trailing.html).

I think this fix might be the reason why the host verification doesn't work anymore. My hypothesis is, that the websocket-client library checks the completed dsn (so hostname and port) against the hostname in the certificate and this worked in the previous version of python, but not in versions which have this fix. So, maybe another websocket library could fix this, but maybe we should somehow test this before we move pyexasol to another library.

**Comment by wildraid** [comment] 2021-01-08 07:11
@tkilias , please note, all IP addresses are resolved prior to any connection attempts.

websocket-client library now gets only IP addresses for connection, not hostnames. For example: `ws://10.10.152.11:8563`. websocket-client does not know the hostname, and there is no way to pass it, unless we use hostname in connection URL (e.g. `ws://exasol1.mlan:8563`), but it will break features related to redundancy.

It would be nice if websocket-client lib creator adds the ability to pass custom hostname to `sslopt`, but it is unlikely to happen.

**Comment by tkilias** [comment] 2021-01-08 10:56
@wildraid ah, I think, I see what I misunderstood.  Ok, pyexasol resolve the hostname to IP for the redundancy feature and because the websocket library doesn't allow the specification of a separate hostname, the verification fails. 
Ah, and the Python 3.6.4 version with option the `ssl.match_hostname = lambda cert, hostname: True` works, because it basically overwrites the hostname match and disables it with this.

Ok, yes with this we are left with the two possible solutions you listed.

**Comment by wildraid** [comment] 2021-01-08 11:35
@tkilias , alternatively, you may consider implementing same (ChaCha20?) encryption for WebSocket protocol.

Websocket connection will be established without encryption, but the frame payloads will be encrypted.

With this approach you will be able to unify the encryption and focus on what is important. Full SSL implementation with certificate authorities, hostname verification etc., makes very little sense in Exasol context. It is DBMS after all, not a public website, not a public webservice, not a public web API.

**Comment by wildraid** [comment] 2021-05-31 09:30
@tkilias 

I've raised a pull request for websocket-client, which may allow us to pass a custom `server_hostname` in `websocket_sslopt`. Let's see how it goes.

I glad to see the `websocket-client` repo being active again!

**Comment by littleK0i** [comment] 2021-11-25 20:06
@AugustVomFass , @tkilias , this issue was finally fixed in 0.23.1+
https://github.com/exasol/pyexasol/blob/master/pyexasol/connection.py#L662-L664

Correct `server_hostname` is now added to `sslopt` automatically. It should work properly even if connection strings contains multiple hostnames, and each hostname can be resolved into multiple IP addresses.

**Closed** 2021-12-06 14:25 UTC
