### ISSUE TITLE
Connection from pyexasol to Exasol SaaS

### ISSUE THREAD

**Issue by exatobr** [exasol/pyexasol#91] opened 2022-05-03 15:22 UTC
I cannot connect to Exasol SaaS using this syntax:
```
C = pyexasol.connect(dsn="DB_connection_string",
                     user="DB_user",
                     refresh_token="DB_PAT"
                     )
```
but using "password" instead of "refresh_token" works fine
```
C = pyexasol.connect(dsn="DB_connection_string",
                     user="DB_user",
                     password="DB_PAT"
                     )
```

**Comment by littleK0i** [comment] 2022-05-03 19:04
What is the error message? Could you also try to enable `debug=True` and post logs here?

Let's take a look.

**Comment by exatobr** [comment] 2022-05-04 09:37
Error Message: Could not connect to Exasol: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)

debug=True does only repeat this error message multiple times

**Comment by littleK0i** [comment] 2022-05-04 09:44
Aha, got it. Using `refresh_token` enables proper certificate verification.
https://github.com/exasol/pyexasol/blob/master/pyexasol/connection.py#L700-L703

Is Exasol SAAS certificate valid in the first place? Does it work with JDBC / ODBC drivers?

**Comment by exatobr** [comment] 2022-05-12 11:42
Seens as if the vertificate could not be found on mac.
I managed to connect if I also use certifi and ssl, maybe that helps to understand the root cause


```
import pyexasol
import certifi
import ssl

C = pyexasol.connect(dsn=conf.get("DB_connection_string"),
                     user=conf.get("DB_user"),
                     refresh_token=conf.get("DB_PAT"),
                     websocket_sslopt = {
                        "cert_reqs": ssl.CERT_REQUIRED,
                        "ca_certs": certifi.where()
                        }
                     )
```

**Comment by littleK0i** [comment] 2022-05-12 12:10
Is JDBC / ODBC working on this machine with Exasol SAAS?

In theory, it might be a problem if system default certificate authority does not recognise SSL certificates generated for Exasol SAAS.

Also, if we enforce `certifi`, it will potentially mess up with any custom "on premise" SSL setups which many people might currently have.

**Comment by littleK0i** [comment] 2022-05-12 13:55
I've checked it with a small SaaS testing cluster and did not detect any issues.

Also, I've checked certificates returned by Exasol:

```
{   'OCSP': ('http://r3.o.lencr.org',),
    'caIssuers': ('http://r3.i.lencr.org/',),
    'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', 'R3'),)),
    'notAfter': 'Jun 15 10:13:31 2022 GMT',
    'notBefore': 'Mar 17 10:13:32 2022 GMT',
    'serialNumber': '03E49B62D405173CF0B2F41BABB9D58290B8',
    'subject': ((('commonName', '*.clusters.exasol.com'),),),
    'subjectAltName': (('DNS', '*.clusters.exasol.com'),),
    'version': 3}
```

```
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = *.clusters.exasol.com
verify return:1
```

The whole chain look OK at first glance.

I suspect you might be having problems specifically with your Python or OS installation. In theory, all other hosts using "Let's Encrypt" should not work for you and return the same error.

Could you try to connect to another host using standard Python?

For example, this host: https://letsencrypt.org/
And this Python package: https://docs.python.org/3/library/urllib.request.html#module-urllib.request

Also, could you ask a colleague to try to reproduce this error? I think, another machine will be ok.

**Comment by luchughes** [comment] 2022-07-15 11:42
@exatobr @littleK0i did you find a solution to this? I have a similar issue in a client's network environment where any of the pyexasol http transport methods just hang indefinitely or time out. execute() works fine and Dbeaver works fine from the same machine but any method like export_to_pandas() fails.

This is a real headscratcher to me. Does http transport utilise a different port or something?

```
2022-07-14 17:49:09.432 [WebSocket request #3]
{
  "command": "getAttributes"
}
2022-07-14 17:49:09.549 [WebSocket response #3]
{
  "status": "ok",
  "attributes": {
    "datetimeFormat": "YYYY-MM-DD HH24:MI:SS.FF6",
    "dateFormat": "YYYY-MM-DD",
    "numericCharacters": ".,",
    "dateLanguage": "ENG",
    "queryTimeout": 0,
    "timezone": "EUROPE/LONDON",
    "timezoneBehavior": "INVALID SHIFT AMBIGUOUS ST",
    "snapshotTransactionsEnabled": true,
    "defaultLikeEscapeCharacter": "\\",
    "autocommit": true,
    "compressionEnabled": true,
    "currentSchema": "ANALYTICS",
    "openTransaction": 0
  }
}
2022-07-14 17:49:09.749 [WebSocket request #4]
{
  "command": "execute",
  "sqlText": "EXPORT analytics.test_for_transport INTO CSV\nAT 'https://192.169.143.58:34045' FILE '000.gz'\nWITH COLUMN NAMES"
}
```
This is the point where it hangs.

**Comment by littleK0i** [comment] 2022-07-15 11:56
It looks like another issue, not related to certificates.

Single-threaded HTTP transport uses the same port to connect: https://github.com/exasol/pyexasol/blob/8b3d0f2a483fab9383ea5987e89fcba73cdf17a5/pyexasol/connection.py#L305

The only difference is that it uses IP address to connect to specific node instead of hostname.

Could you try running the same code from different machine? Maybe Mac / Linux, or from an actual server. With Windows too many things can go wrong.

**Comment by luchughes** [comment] 2022-07-15 12:05
Thanks for the very quick response! I've tried from 2 different machines within the client network and get the same result in both, but I did try from another laptop on a different network and it works:

```
2022-07-14 17:49:27.065 [WebSocket request #3]
{
  "command": "getAttributes"
}
2022-07-14 17:49:27.178 [WebSocket response #3]
{
  "status": "ok",
  "attributes": {
    "datetimeFormat": "YYYY-MM-DD HH24:MI:SS.FF6",
    "dateFormat": "YYYY-MM-DD",
    "numericCharacters": ".,",
    "dateLanguage": "ENG",
    "queryTimeout": 0,
    "timezone": "EUROPE/LONDON",
    "timezoneBehavior": "INVALID SHIFT AMBIGUOUS ST",
    "snapshotTransactionsEnabled": true,
    "defaultLikeEscapeCharacter": "\\",
    "autocommit": true,
    "compressionEnabled": true,
    "currentSchema": "ANALYTICS",
    "openTransaction": 0
  }
}
2022-07-14 17:49:27.305 [WebSocket request #4]
{
  "command": "execute",
  "sqlText": "EXPORT (\nSelect * from test_for_transport\n) INTO CSV\nAT 'https://192.169.143.25:38263' FILE '000.gz'\nWITH COLUMN NAMES"
}
2022-07-14 17:49:28.618 [WebSocket response #4]
{
  "status": "ok",
  "responseData": {
    "results": [
      {
        "resultType": "rowCount",
        "rowCount": 3
      }
    ],
    "numResults": 1
  }
}
2022-07-14 17:49:28.622 [WebSocket request #5]
{
  "command": "disconnect"
}
2022-07-14 17:49:28.655 [WebSocket response #5]
{
  "status": "ok"
}
2022-07-14 17:49:28.655 [WebSocket connection close]
```

I'm a bit baffled as both all machines have IPv4 addresses in whitelisted ranges and ODBC and pyexasol execute() behaviour is identical, it's just http transport that is having this issue.

**Comment by luchughes** [comment] 2022-07-15 12:09
Also, I ran from a kubernetes pod linux environment also within the client's network and got an identical issue to the first one

**Comment by littleK0i** [comment] 2022-07-15 13:25
How about `exajload` or standard Exasol JDBC driver? Does it work for IMPORT (from local file)? Internally, JDBC driver should use the same approach.

What if you try to connect to Exasol using IPv4 address in DSN instead of hostname?

Does client have some fancy "protection" software? HTTP transport is a little bit odd. It does not use SSL immediately after connection. Instead, it sends and receives some un-encrypted data, and waits for incoming request from Exasol. It might be considered suspicious for software which tries to analyse network packets and figure out what is going on.

**Comment by littleK0i** [comment] 2022-07-15 13:28
Also, you may always install "pyexasol" locally for development using `pip install -e .` and start debugging around this piece of code: https://github.com/exasol/pyexasol/blob/master/pyexasol/http_transport.py#L369-L382

This is where initial connection happens.

And this is the response handler: https://github.com/exasol/pyexasol/blob/master/pyexasol/http_transport.py#L473-L494

**Comment by luchughes** [comment] 2022-07-15 13:32
Thanks for the pointers - I'll continue to debug with these and let you know if I have any success!

**Comment by littleK0i** [comment] 2022-07-18 15:18
This is IP in Exasol private network.

When pyexasol (or JDBC) connects and sends a special packet, Exasol creates some sort of "tunnel" in its private network routed into HTTP transport connections. The address + port of this tunnel is returned to client and is used while building IMPORT or EXPORT sql query.

Normally, you may ignore these addresses. Actual public network connectivity uses public IP address and port.

**Comment by exatobr** [comment] 2022-09-16 10:36
I suggest to close this issue

**Comment by littleK0i** [comment] 2022-09-18 14:28
Let's close it, I agree. Let's encrypt root certs should be largely available on all machines nowadays.

I don't think it will be widespread issue. But if it does, we can always reopen.

**Closed by littleK0i** 2022-09-18 14:28 UTC
Labels: feature
